In [ ]:
# Import libraries
import pandas as pd
import sys
import warnings
from pathlib import Path

# suppress warnings in notebook
warnings.filterwarnings('ignore')

sys.path.append(str(Path('..').resolve() / 'src'))

from preprocessing import WhatsAppParser

**Data Source**  
`_chat.txt` : didapat dari grup baca alkitab whatsapp GRII Solo.

---
## 1. data chat.txt

In [ ]:
CHAT_FILE = Path('../data/raw/whatsapp_exports/_chat.txt')

# ukuran file
print("Ukuran file:", CHAT_FILE.stat().st_size, "bytes")

# jumlah baris
with CHAT_FILE.open(encoding="utf-8") as f:
    lines = f.readlines()
print("Jumlah baris:", len(lines))

Ukuran file: 3622892 bytes
Jumlah baris: 74352

In [ ]:
# Lihat beberapa baris pertama (preview)
with CHAT_FILE.open(encoding="utf-8") as f:
    for i in range(10):  # tampilkan 10 baris pertama
        print(f.readline().strip())

---
## 2. Setelah Whatsapp parsing ()

In [ ]:
parser = WhatsAppParser()

df_after_WA_parse = parser.parse_chat_file(CHAT_FILE)
df_after_WA_parse.info()

In [ ]:
df_after_WA_parse.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>timestamp</th>
      <th>sender</th>
      <th>message</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2020-08-02 11:41:31</td>
      <td>Bible Reading Cycle 2</td>
      <td>Pesan dan panggilan terenkripsi secara end-to-...</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2020-08-02 11:41:31</td>
      <td>Lenny Pandjidharma</td>
      <td>Lenny Pandjidharma membuat grup “Bible Reading...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2020-08-02 11:41:31</td>
      <td>Bible Reading Cycle 2</td>
      <td>Lenny Pandjidharma menambahkan Anda</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2020-08-02 11:41:43</td>
      <td>Vik. Dessy Waiman</td>
      <td>Lenny Pandjidharma menambahkan Vik. Dessy Waiman</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2020-08-02 11:42:23</td>
      <td>Lenny Pandjidharma</td>
      <td>Lenny Pandjidharma mengubah deskripsi grup</td>
    </tr>
  </tbody>
</table>
</div>

---
## 3. reviewed_message.csv

**Data Source**  
`reviewed_messages.csv` — manually labeled:
- `report` — reading progress update  
- `not report` — system messages, discussions, general chat

In [ ]:
from config import PROCESSED_DIR

DATA_PATH = PROCESSED_DIR / 'reviewed_messages.csv'
df_reviewed_messages = pd.read_csv(DATA_PATH)
df_reviewed_messages.info()

In [ ]:
df_reviewed_messages.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>timestamp</th>
      <th>sender</th>
      <th>message</th>
      <th>category</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>8/2/2020 11:41</td>
      <td>Bible Reading Cycle 2</td>
      <td>Pesan dan panggilan terenkripsi secara end-to-...</td>
      <td>not report</td>
    </tr>
    <tr>
      <th>1</th>
      <td>8/2/2020 11:41</td>
      <td>Lenny Pandjidharma</td>
      <td>Lenny Pandjidharma membuat grup “Bible Reading...</td>
      <td>not report</td>
    </tr>
    <tr>
      <th>2</th>
      <td>8/2/2020 11:41</td>
      <td>Bible Reading Cycle 2</td>
      <td>Lenny Pandjidharma menambahkan Anda</td>
      <td>not report</td>
    </tr>
    <tr>
      <th>3</th>
      <td>8/2/2020 11:41</td>
      <td>Vik. Dessy Waiman</td>
      <td>Lenny Pandjidharma menambahkan Vik. Dessy Waiman</td>
      <td>not report</td>
    </tr>
    <tr>
      <th>4</th>
      <td>8/2/2020 11:42</td>
      <td>Lenny Pandjidharma</td>
      <td>Lenny Pandjidharma mengubah deskripsi grup</td>
      <td>not report</td>
    </tr>
  </tbody>
</table>
</div>